---  # default config

# APIs
cdc_api_key: <your Crypto.com Exchange API key here>
cdc_api_secret: <your Crypto.com Exchange API private key here>
krk_api_key: <your Kraken Exchange API key here>
krk_api_secret: <your Kraken Exchange API private key here>
bnb_api_key: <your Binance Exchange API key here>
bnb_api_secret: <your Binance Exchange API private key here>

# CRYPTO.COM SETTINGS
cdc_trading_pair: BTC_USDC # This must be one of the pairs listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/pairs.py
cdc_base_currency: BTC # this must be one of the currencies listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/coins.py
cdc_target_currency: USDC # this must be one of the currencies listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/coins.py
cdc_max_decimals_buy: 6 # This is the limit Crypto.com has on ETH_BTC pair https://crypto.com/exchange/trade/spot/ETH_BTC
cdc_max_decimals_sell: 3


# KRAKEN SETTINGS
krk_trading_pair: XXBTZEUR
krk_buy_trading_pair: XXBTZEUR
krk_buy_trading_pair_step2: XXRPXXBT
krk_buy_trading_pair_step3: XXRPZEUR
krk_base_currency: XXBT # this must be one of the currencies listed in https://api.kraken.com/0/public/Assets (key value, not the 'altname' value)
krk_target_currency: ZEUR # this must be one of the currencies listed in https://api.kraken.com/0/public/Assets (key value, not the 'altname' value
krk_max_decimals_buy: 3
krk_max_decimals_sell: 6
krk_xrp_address: <your XRP address in Kraken>
krk_xrp_address_tag: <your XRP address tag in Kraken>
krk_bnb_xrp_address_key: <your XRP address key in Kraken to send XRP to Binance>


# BINANCE SETTINGS
bnb_trading_pair: BTCEUR
bnb_buy_trading_pair: XRPBTC
bnb_base_currency: BTC
bnb_target_currency: EUR
bnb_max_decimals_buy: 6
bnb_max_decimals_sell: 6


# ARBITRITO SETTINGS
btc_amount_in_exchanges: 0.003606

# ARBITRITO MODES
safe_mode_on: True # True => no real trades will be made; False => real trades will be made
test_mode_on: True # (True => Arbitrito will run just once ; False => Arbitrito will run forever until stopped)

# LOOP SETTINGS
seconds_between_iterations: 5
